import React from 'react';
import { motion } from 'framer-motion';
import { PopCard, containerVariants } from '../ui/PopCard';
import { Search, ClipboardList, BarChart2, Video, Mail, MessageSquare, Coffee, ArrowUpRight, ChevronRight } from 'lucide-react';

const HelpCenter = () => (
  <motion.div variants={containerVariants} initial="hidden" animate="show">
    <PopCard style={{ background: '#0284c7', color: 'white', padding: '4rem 2rem', textAlign: 'center', border: 'none', marginBottom: '3rem' }}>
      <h1 style={{ fontSize: '3rem', fontWeight: 800, marginBottom: '2rem' }}>How can we help you today?</h1>
      <div style={{ position: 'relative', maxWidth: '600px', margin: '0 auto' }}><Search size={20} style={{ position: 'absolute', left: '1.5rem', top: '50%', transform: 'translateY(-50%)', color: 'gray' }} /><input type="text" placeholder="Search for solutions..." style={{ width: '100%', padding: '1.25rem 1.5rem 1.25rem 3.5rem', borderRadius: '30px', border: 'none', fontSize: '1.1rem', outline: 'none' }} /></div>
      <div style={{ display: 'flex', justifyContent: 'center', gap: '1rem', marginTop: '2rem' }}>{['Canvas Login', 'Course Enrollment', 'VPN Access', 'Tuition Fees'].map(tag => ( <span key={tag} style={{ background: 'rgba(255,255,255,0.2)', padding: '0.5rem 1.25rem', borderRadius: '20px', fontSize: '0.85rem', fontWeight: 600, cursor: 'pointer' }}>{tag}</span> ))}</div>
    </PopCard>
    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '2rem' }}><div><h2 style={{ fontSize: '1.8rem', fontWeight: 800, color: 'var(--text-main)' }}>Top Help Topics</h2><p style={{ color: 'var(--text-muted)' }}>The most frequently accessed resources for our scholars.</p></div><span style={{ color: '#0284c7', fontWeight: 700, cursor: 'pointer' }}>View All Categories &rarr;</span></div>
    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '2rem', marginBottom: '4rem' }}>
      <PopCard style={{ padding: '2rem', cursor: 'pointer', display: 'flex', flexDirection: 'column', gap: '1.5rem' }}><div style={{ background: 'rgba(2, 132, 199, 0.1)', width: '50px', height: '50px', borderRadius: '12px', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#0284c7' }}><ClipboardList size={24}/></div><div><h3 style={{ fontSize: '1.3rem', fontWeight: 800, color: 'var(--text-main)', marginBottom: '0.5rem' }}>Submitting Assignments</h3><p style={{ fontSize: '0.95rem', color: 'var(--text-muted)', lineHeight: 1.5 }}>Detailed guide on file formats, deadlines, and confirmation receipts for all courses.</p></div><span style={{ color: '#0284c7', fontWeight: 700, fontSize: '0.9rem', marginTop: 'auto', display: 'flex', alignItems: 'center', gap: '0.4rem' }}>Read Guide <ArrowUpRight size={16}/></span></PopCard>
      <PopCard style={{ padding: '2rem', cursor: 'pointer', display: 'flex', flexDirection: 'column', gap: '1.5rem' }}><div style={{ background: 'rgba(2, 132, 199, 0.1)', width: '50px', height: '50px', borderRadius: '12px', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#0284c7' }}><BarChart2 size={24}/></div><div><h3 style={{ fontSize: '1.3rem', fontWeight: 800, color: 'var(--text-main)', marginBottom: '0.5rem' }}>Accessing Grades</h3><p style={{ fontSize: '0.95rem', color: 'var(--text-muted)', lineHeight: 1.5 }}>Learn where to find feedback from faculty and how to view your historical GPA data.</p></div><span style={{ color: '#0284c7', fontWeight: 700, fontSize: '0.9rem', marginTop: 'auto', display: 'flex', alignItems: 'center', gap: '0.4rem' }}>Check Grades <ArrowUpRight size={16}/></span></PopCard>
      <PopCard style={{ padding: '2rem', cursor: 'pointer', display: 'flex', flexDirection: 'column', gap: '1.5rem' }}><div style={{ background: 'rgba(2, 132, 199, 0.1)', width: '50px', height: '50px', borderRadius: '12px', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#0284c7' }}><Video size={24}/></div><div><h3 style={{ fontSize: '1.3rem', fontWeight: 800, color: 'var(--text-main)', marginBottom: '0.5rem' }}>Zoom Troubleshooting</h3><p style={{ fontSize: '0.95rem', color: 'var(--text-muted)', lineHeight: 1.5 }}>Fixing common audio, video, and connection issues during your live seminar sessions.</p></div><span style={{ color: '#0284c7', fontWeight: 700, fontSize: '0.9rem', marginTop: 'auto', display: 'flex', alignItems: 'center', gap: '0.4rem' }}>Fix Issues <ArrowUpRight size={16}/></span></PopCard>
    </div>
    <div style={{ display: 'grid', gridTemplateColumns: '2fr 1fr', gap: '3rem' }}>
      <div>
        <h2 style={{ fontSize: '1.5rem', fontWeight: 800, color: 'var(--text-main)', marginBottom: '2rem' }}>Recent Articles</h2>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
          <PopCard style={{ display: 'flex', gap: '1.5rem', padding: '1.5rem', alignItems: 'center' }}><div style={{ width: '120px', height: '80px', borderRadius: '12px', background: 'var(--border)', overflow: 'hidden' }}><img src="https://images.unsplash.com/photo-1455309014309-98f996312f2f?q=80&w=400" alt="Writing" style={{width:'100%', height:'100%', objectFit:'cover'}}/></div><div><div style={{ display: 'flex', gap: '1rem', alignItems: 'center', marginBottom: '0.5rem' }}><span style={{ background: 'rgba(2, 132, 199, 0.1)', color: '#0284c7', padding: '0.2rem 0.6rem', borderRadius: '12px', fontSize: '0.7rem', fontWeight: 800 }}>TUTORIAL</span><span style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>Oct 24, 2023</span></div><h3 style={{ fontSize: '1.1rem', fontWeight: 800, color: 'var(--text-main)', marginBottom: '0.4rem' }}>Mastering the Digital Portfolio</h3><p style={{ fontSize: '0.9rem', color: 'var(--text-muted)' }}>How to curate and submit your final year creative works through the streamline portal.</p></div></PopCard>
          <PopCard style={{ display: 'flex', gap: '1.5rem', padding: '1.5rem', alignItems: 'center' }}><div style={{ width: '120px', height: '80px', borderRadius: '12px', background: 'var(--border)', overflow: 'hidden' }}><img src="https://images.unsplash.com/photo-1522071820081-009f0129c71c?q=80&w=400" alt="Workspace" style={{width:'100%', height:'100%', objectFit:'cover'}}/></div><div><div style={{ display: 'flex', gap: '1rem', alignItems: 'center', marginBottom: '0.5rem' }}><span style={{ background: 'rgba(16, 185, 129, 0.1)', color: '#10b981', padding: '0.2rem 0.6rem', borderRadius: '12px', fontSize: '0.7rem', fontWeight: 800 }}>COMMUNITY</span><span style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>Oct 21, 2023</span></div><h3 style={{ fontSize: '1.1rem', fontWeight: 800, color: 'var(--text-main)', marginBottom: '0.4rem' }}>Collaborative Workspace Tips</h3><p style={{ fontSize: '0.9rem', color: 'var(--text-muted)' }}>Best practices for using shared digital canvases during peer review sessions.</p></div></PopCard>
        </div>
      </div>
      <PopCard style={{ background: 'var(--bg-main)' }}>
        <h2 style={{ fontSize: '1.5rem', fontWeight: 800, color: 'var(--text-main)', marginBottom: '0.5rem' }}>Need More Help?</h2><p style={{ color: 'var(--text-muted)', fontSize: '0.95rem', marginBottom: '2rem' }}>Our specialized teams are ready to support your academic journey.</p>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem', marginBottom: '2rem' }}>
          <div style={{ background: 'var(--bg-card)', padding: '1.25rem', borderRadius: '12px', display: 'flex', justifyContent: 'space-between', alignItems: 'center', cursor: 'pointer', border: '1px solid var(--border)' }}><div><h4 style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', fontWeight: 800, color: 'var(--text-main)' }}><Mail size={18} color="#0284c7"/> Email Support</h4><span style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>Response in 24h</span></div><ChevronRight size={20} color="var(--text-muted)"/></div>
          <div style={{ background: 'var(--bg-card)', padding: '1.25rem', borderRadius: '12px', display: 'flex', justifyContent: 'space-between', alignItems: 'center', cursor: 'pointer', border: '1px solid var(--border)' }}><div><h4 style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', fontWeight: 800, color: 'var(--text-main)' }}><MessageSquare size={18} color="#10b981"/> Live Chat</h4><span style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>Active now</span></div><ChevronRight size={20} color="var(--text-muted)"/></div>
          <div style={{ background: 'var(--bg-card)', padding: '1.25rem', borderRadius: '12px', display: 'flex', justifyContent: 'space-between', alignItems: 'center', cursor: 'pointer', border: '1px solid var(--border)' }}><div><h4 style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', fontWeight: 800, color: 'var(--text-main)' }}><Coffee size={18} color="#f59e0b"/> Faculty Lounge</h4><span style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>Office Hours</span></div><ChevronRight size={20} color="var(--text-muted)"/></div>
        </div>
        <div style={{ background: 'rgba(2, 132, 199, 0.05)', padding: '1.25rem', borderRadius: '12px', border: '1px solid rgba(2, 132, 199, 0.2)' }}><h5 style={{ fontWeight: 800, fontSize: '0.9rem', color: 'var(--text-main)', marginBottom: '0.5rem' }}>Emergency?</h5><p style={{ fontSize: '0.8rem', color: 'var(--text-muted)', marginBottom: '1rem' }}>For immediate account lockouts, call our 24/7 hotline.</p><span style={{ color: '#0284c7', fontWeight: 800 }}>+1 (800) SCHOLAR</span></div>
      </PopCard>
    </div>
  </motion.div>
);
export default HelpCenter;