import React from 'react';
import { motion } from 'framer-motion';
import { PopCard, containerVariants } from '../ui/PopCard';
import { BarChart2, TrendingUp, ClipboardList, CheckCircle, Search, SlidersHorizontal, AlertTriangle, Edit2 } from 'lucide-react';
import { students, getScoreColor } from '../../data/mockData';

const Grading = () => (
  <motion.div variants={containerVariants} initial="hidden" animate="show" style={{ display: 'flex', flexDirection: 'column', gap: '2.5rem' }}>
    <h1 style={{ fontSize: '2.2rem', fontWeight: 800, marginBottom: '-1rem' }}>Classroom Gradebook</h1>
    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1.5fr 1fr', gap: '1.5rem' }}>
      <PopCard style={{ display: 'flex', flexDirection: 'column', justifyContent: 'center', position: 'relative', overflow: 'hidden' }}><BarChart2 size={120} color="var(--bg-main)" style={{ position: 'absolute', right: '-20px', bottom: '-20px', opacity: 0.5 }} /><p style={{ color: 'var(--text-muted)', fontSize: '0.9rem', fontWeight: 600, marginBottom: '0.5rem' }}>Class Average Score</p><h2 style={{ fontSize: '3rem', fontWeight: 800, color: '#0284c7', lineHeight: 1, marginBottom: '0.5rem' }}>84.2%</h2><span style={{ color: '#10b981', fontSize: '0.85rem', fontWeight: 700, display: 'flex', alignItems: 'center', gap: '0.3rem' }}><TrendingUp size={14}/> +2.4% from last month</span></PopCard>
      <PopCard style={{ display: 'flex', flexDirection: 'column', justifyContent: 'center' }}><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem' }}><p style={{ color: 'var(--text-main)', fontSize: '1rem', fontWeight: 700 }}>Assignment Velocity</p><span style={{ color: 'var(--text-muted)', fontSize: '0.7rem', fontWeight: 700, textTransform: 'uppercase' }}>Active Quarter</span></div><div style={{ marginBottom: '1.25rem' }}><div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.85rem', fontWeight: 600, marginBottom: '0.5rem' }}><span>Project Beta: UI Prototypes</span><span style={{ color: '#2563eb' }}>92%</span></div><div style={{ width: '100%', height: '8px', background: 'var(--bg-main)', borderRadius: '4px' }}><div style={{ width: '92%', height: '100%', background: '#2563eb', borderRadius: '4px' }}></div></div></div><div><div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.85rem', fontWeight: 600, marginBottom: '0.5rem' }}><span>Weekly Quiz: Typography</span><span style={{ color: '#10b981' }}>78%</span></div><div style={{ width: '100%', height: '8px', background: 'var(--bg-main)', borderRadius: '4px' }}><div style={{ width: '78%', height: '100%', background: '#10b981', borderRadius: '4px' }}></div></div></div></PopCard>
      <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}><PopCard style={{ flex: 1, background: '#fef3c7', borderColor: '#fde68a', display: 'flex', alignItems: 'center', gap: '1.5rem', padding: '1rem 1.5rem' }}><div style={{ background: 'rgba(245, 158, 11, 0.2)', padding: '0.75rem', borderRadius: '12px', color: '#d97706' }}><ClipboardList size={24}/></div><div><h3 style={{ fontSize: '1.8rem', fontWeight: 800, color: '#92400e', lineHeight: 1 }}>14</h3><span style={{ fontSize: '0.8rem', fontWeight: 600, color: '#b45309' }}>Pending Reviews</span></div></PopCard><PopCard style={{ flex: 1, background: '#dcfce7', borderColor: '#bbf7d0', display: 'flex', alignItems: 'center', gap: '1.5rem', padding: '1rem 1.5rem' }}><div style={{ background: 'rgba(16, 185, 129, 0.2)', padding: '0.75rem', borderRadius: '12px', color: '#059669' }}><CheckCircle size={24}/></div><div><h3 style={{ fontSize: '1.8rem', fontWeight: 800, color: '#166534', lineHeight: 1 }}>28</h3><span style={{ fontSize: '0.8rem', fontWeight: 600, color: '#15803d' }}>Students On Track</span></div></PopCard></div>
    </div>
    <PopCard style={{ padding: '0' }}>
      <div style={{ padding: '1.5rem', borderBottom: '1px solid var(--border)', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}><div><h3 style={{ fontSize: '1.2rem', fontWeight: 700 }}>Detailed Records</h3><p style={{ fontSize: '0.85rem', color: 'var(--text-muted)' }}>Manage student performance across all modules.</p></div><div style={{ display: 'flex', gap: '1rem' }}><div style={{ position: 'relative' }}><Search size={14} style={{ position: 'absolute', left: '1rem', top: '50%', transform: 'translateY(-50%)', color: 'var(--text-muted)' }} /><input type="text" placeholder="Search students..." style={{ padding: '0.5rem 1rem 0.5rem 2.2rem', borderRadius: '20px', border: '1px solid var(--border)', background: 'var(--bg-main)', outline: 'none', fontSize: '0.85rem' }} /></div></div></div>
      <table style={{ width: '100%', borderCollapse: 'collapse', textAlign: 'left' }}>
        <thead><tr style={{ borderBottom: '1px solid var(--border)', color: 'var(--text-muted)', fontSize: '0.75rem', textTransform: 'uppercase', letterSpacing: '0.5px' }}><th style={{ padding: '1.25rem 1.5rem', fontWeight: 700 }}>Student Name</th><th style={{ padding: '1.25rem 1rem', fontWeight: 700 }}>Attendance</th><th style={{ padding: '1.25rem 1rem', fontWeight: 700 }}>Average</th><th style={{ padding: '1.25rem 1.5rem', fontWeight: 700 }}>Status</th></tr></thead>
        <tbody>{students.map((student, i) => ( <tr key={student.id} style={{ borderBottom: i !== students.length - 1 ? '1px solid var(--border)' : 'none' }}><td style={{ padding: '1.5rem', display: 'flex', alignItems: 'center', gap: '1rem' }}><div style={{ width: '35px', height: '35px', borderRadius: '50%', background: 'var(--accent)', color: 'white', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: 'bold', fontSize: '0.9rem' }}>{student.avatar}</div><div><p style={{ fontWeight: 700, fontSize: '0.9rem', color: 'var(--text-main)' }}>{student.name}</p><span style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>ID: #{student.id}</span></div></td><td style={{ padding: '1.5rem', fontSize: '0.9rem', fontWeight: 600 }}>{student.att}</td><td style={{ padding: '1.5rem', fontSize: '0.95rem', fontWeight: 800, color: '#0284c7' }}>{student.grade}</td><td style={{ padding: '1.5rem' }}><span style={{ background: student.statusBg, color: student.statusColor, padding: '0.4rem 1rem', borderRadius: '20px', fontSize: '0.75rem', fontWeight: 800, textTransform: 'uppercase' }}>{student.status}</span></td></tr> ))}</tbody>
      </table>
    </PopCard>
  </motion.div>
);
export default Grading;