import React from 'react';
import { motion } from 'framer-motion';
import { PopCard, containerVariants } from '../ui/PopCard';
import { Users, Zap, Plus, BookOpen, Calendar as CalendarIcon } from 'lucide-react';

const MyClasses = () => (
  <motion.div variants={containerVariants} initial="hidden" animate="show">
    <h1 style={{ fontSize: '2.2rem', fontWeight: 800, marginBottom: '2.5rem' }}>My Classes</h1>
    <div style={{ display: 'grid', gridTemplateColumns: '2.2fr 1fr', gap: '2.5rem' }}>
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1.5rem' }}>
        <PopCard style={{ padding: 0, overflow: 'hidden' }}>
          <div style={{ position: 'relative', height: '160px' }}><img src="https://images.unsplash.com/photo-1635070041078-e363dbe005cb?q=80&w=600" alt="Physics" style={{ width: '100%', height: '100%', objectFit: 'cover' }} /><div style={{ position: 'absolute', inset: 0, background: 'linear-gradient(135deg, #0f172a 0%, #1e293b 100%)', opacity: 0.7 }} /><div style={{ position: 'absolute', top: '1rem', right: '1rem', background: 'rgba(0,0,0,0.6)', color: 'white', padding: '0.3rem 0.8rem', borderRadius: '15px', fontSize: '0.75rem', display: 'flex', gap: '0.5rem', alignItems: 'center' }}> <Users size={14}/> 28/30</div></div>
          <div style={{ padding: '1.5rem' }}><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem' }}><h3 style={{ fontSize: '1.3rem', fontWeight: 800 }}>Advanced Physics</h3><span style={{ background: '#dcfce7', color: '#166534', padding: '0.3rem 0.8rem', borderRadius: '12px', fontSize: '0.7rem', fontWeight: 800 }}>ACTIVE</span></div><div style={{ display: 'flex', flexDirection: 'column', gap: '1.25rem', marginBottom: '1.5rem' }}><div><div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.8rem', fontWeight: 600, marginBottom: '0.4rem' }}><span>Quantum Mechanics Quiz</span><span>85%</span></div><div style={{ height: '6px', background: 'var(--bg-main)', borderRadius: '3px' }}><div style={{ width: '85%', height: '100%', background: '#2563eb', borderRadius: '3px' }}></div></div></div><div><div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.8rem', fontWeight: 600, marginBottom: '0.4rem' }}><span>Lab Report: Wave Optics</span><span>42%</span></div><div style={{ height: '6px', background: 'var(--bg-main)', borderRadius: '3px' }}><div style={{ width: '42%', height: '100%', background: '#2563eb', borderRadius: '3px' }}></div></div></div></div><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderTop: '1px solid var(--border)', paddingTop: '1.25rem' }}><div><p style={{ fontSize: '0.7rem', color: 'var(--text-muted)', fontWeight: 700, textTransform: 'uppercase', marginBottom:'0.2rem' }}>Avg. Grade</p><span style={{ fontSize: '1.2rem', fontWeight: 800, color: '#0284c7' }}>A- (92%)</span></div><button className="btn primary-btn" style={{ padding: '0.6rem 1.5rem', borderRadius: '25px', fontSize: '0.9rem' }}>Enter</button></div></div>
        </PopCard>
        <PopCard style={{ padding: 0, overflow: 'hidden' }}>
          <div style={{ position: 'relative', height: '160px' }}><img src="https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?q=80&w=600" alt="Poetry" style={{ width: '100%', height: '100%', objectFit: 'cover' }} /><div style={{ position: 'absolute', inset: 0, background: 'linear-gradient(135deg, #854d0e 0%, #f59e0b 100%)', opacity: 0.7 }} /><div style={{ position: 'absolute', top: '1rem', right: '1rem', background: 'rgba(0,0,0,0.6)', color: 'white', padding: '0.3rem 0.8rem', borderRadius: '15px', fontSize: '0.75rem', display: 'flex', gap: '0.5rem', alignItems: 'center' }}> <Users size={14}/> 22/25</div></div>
          <div style={{ padding: '1.5rem' }}><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem' }}><h3 style={{ fontSize: '1.3rem', fontWeight: 800 }}>Modernist Poetry</h3><span style={{ background: '#dcfce7', color: '#166534', padding: '0.3rem 0.8rem', borderRadius: '12px', fontSize: '0.7rem', fontWeight: 800 }}>ACTIVE</span></div><div style={{ display: 'flex', flexDirection: 'column', gap: '1.25rem', marginBottom: '1.5rem' }}><div><div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.8rem', fontWeight: 600, marginBottom: '0.4rem' }}><span>T.S. Eliot Analysis</span><span>95%</span></div><div style={{ height: '6px', background: 'var(--bg-main)', borderRadius: '3px' }}><div style={{ width: '95%', height: '100%', background: '#10b981', borderRadius: '3px' }}></div></div></div><div><div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.8rem', fontWeight: 600, marginBottom: '0.4rem' }}><span>The Waste Land Drafts</span><span>60%</span></div><div style={{ height: '6px', background: 'var(--bg-main)', borderRadius: '3px' }}><div style={{ width: '60%', height: '100%', background: '#2563eb', borderRadius: '3px' }}></div></div></div></div><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderTop: '1px solid var(--border)', paddingTop: '1.25rem' }}><div><p style={{ fontSize: '0.7rem', color: 'var(--text-muted)', fontWeight: 700, textTransform: 'uppercase', marginBottom:'0.2rem' }}>Avg. Grade</p><span style={{ fontSize: '1.2rem', fontWeight: 800, color: '#0284c7' }}>B+ (88%)</span></div><button className="btn primary-btn" style={{ padding: '0.6rem 1.5rem', borderRadius: '25px', fontSize: '0.9rem' }}>Enter</button></div></div>
        </PopCard>
      </div>
      <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
        <PopCard style={{ background: '#f8fafc' }}>
          <h3 style={{ fontWeight: 700, fontSize: '1.1rem', marginBottom: '1.5rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}><Zap color="var(--accent)" size={20}/> Quick Actions</h3>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
            <button style={{ background: 'white', border: '1px solid var(--border)', padding: '1rem', borderRadius: '12px', display: 'flex', alignItems: 'center', gap: '1rem', fontWeight: 600, color: 'var(--text-main)', cursor: 'pointer', transition: 'all 0.2s' }}><div style={{ background: '#e0f2fe', color: '#0284c7', padding: '0.4rem', borderRadius: '50%' }}><Plus size={16}/></div> Create New Course</button>
            <button style={{ background: 'white', border: '1px solid var(--border)', padding: '1rem', borderRadius: '12px', display: 'flex', alignItems: 'center', gap: '1rem', fontWeight: 600, color: 'var(--text-main)', cursor: 'pointer', transition: 'all 0.2s' }}><div style={{ background: '#dcfce7', color: '#10b981', padding: '0.4rem', borderRadius: '50%' }}><BookOpen size={16}/></div> Bulk Grade</button>
            <button style={{ background: 'white', border: '1px solid var(--border)', padding: '1rem', borderRadius: '12px', display: 'flex', alignItems: 'center', gap: '1rem', fontWeight: 600, color: 'var(--text-main)', cursor: 'pointer', transition: 'all 0.2s' }}><div style={{ background: '#fef3c7', color: '#d97706', padding: '0.4rem', borderRadius: '50%' }}><CalendarIcon size={16}/></div> Schedule Seminar</button>
          </div>
        </PopCard>
      </div>
    </div>
  </motion.div>
);

export default MyClasses;